import Head from 'next/head'
import { w } from 'windstitch';
import { Dropdown } from "flowbite-react";

const Home = () => {
  const H1 = w.h1(`text-3xl font-bold underline text-yellow-700`)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <H1>
        Hello World!
      </H1>
      <hr />
      <Dropdown label="Dropdown">
        <Dropdown.Item>
          Dashboard
        </Dropdown.Item>
        <Dropdown.Item>
          Settings
        </Dropdown.Item>
        <Dropdown.Item>
          Earnings
        </Dropdown.Item>
        <Dropdown.Item>
          Sign out
        </Dropdown.Item>
      </Dropdown>
    </>
  )
}

export default Home